# Based on
name: Clean up Docker registry

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Note: the image name must be lowercase.
  IMAGE_NAME: tlomodel/actions-runner

jobs:
  cleanup-registry:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'actions-runner'
          package-type: 'container'
          min-versions-to-keep: 4
