name: lint

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files
